name: bus_tracker_mvp
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.0
  google_maps_flutter: ^2.6.0
  geolocator: ^12.0.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.0.0
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
